"""initial migration.

Revision ID: 04767661a43d
Revises: 
Create Date: 2023-08-07 02:16:08.386685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04767661a43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('email', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'comment', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='unique')
    op.drop_column('comment', 'email')
    # ### end Alembic commands ###
